#!/usr/bin/env bash
set -euo pipefail
# scripts/tools/build_wiki_docx.sh — build the English wiki docx guides from docs/*.md
# Version: 1.1.0
#
# Markdown under docs/ is the source of truth (docs/SHAREPOINT_PUBLICATION.md).
# This tool only renders it: one docx per row of docs/wiki/manifest.tsv.
# Runs on a workstation (needs pandoc >= 2.17 and python3), not on the R nodes.
#
# Usage:
#   bash scripts/tools/build_wiki_docx.sh [--out DIR] [--only ID] [-h|--help]
#     --out DIR   output directory (default: docs/wiki)
#     --only ID   build only the guide with this manifest id

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'; BLUE='\033[0;34m'; NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
DOCS_DIR="${REPO_ROOT}/docs"
MANIFEST="${DOCS_DIR}/wiki/manifest.tsv"
FILTER="${SCRIPT_DIR}/wiki/wiki_filter.lua"
MAKE_REF="${SCRIPT_DIR}/wiki/make_reference_docx.py"
OUT_DIR="${DOCS_DIR}/wiki"
ONLY=""

info() { printf "${BLUE}[INFO]${NC} %s\n" "$*"; }
ok()   { printf "${GREEN}[ OK ]${NC} %s\n" "$*"; }
warn() { printf "${YELLOW}[WARN]${NC} %s\n" "$*" >&2; }
die()  { printf "${RED}[FAIL]${NC} %s\n" "$*" >&2; exit 1; }

usage() { sed -n '9,13p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; }

while [[ $# -gt 0 ]]; do
    case "$1" in
        --out)  [[ -n "${2:-}" ]] || die "--out requires a directory"; OUT_DIR="$2"; shift 2 ;;
        --only) [[ -n "${2:-}" ]] || die "--only requires a guide id"; ONLY="$2"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) die "unknown argument: $1 (see --help)" ;;
    esac
done

for cmd in pandoc python3 git; do
    command -v "$cmd" >/dev/null 2>&1 || die "missing dependency: $cmd"
done
pandoc_ver="$(pandoc --version | awk 'NR==1{print $2}')"
if [[ "$(printf '%s\n2.17\n' "$pandoc_ver" | sort -V | head -1)" != "2.17" ]]; then
    die "pandoc ${pandoc_ver} too old (need >= 2.17 for --file-scope link ids and pandoc.walk_block)"
fi
[[ -f "$MANIFEST" ]] || die "manifest not found: $MANIFEST"
[[ -f "$FILTER" && -f "$MAKE_REF" ]] || die "build assets missing under ${SCRIPT_DIR}/wiki/"
mkdir -p "$OUT_DIR" || die "cannot create output dir: $OUT_DIR"

WORK="$(mktemp -d "${TMPDIR:-/tmp}/wiki_docx.XXXXXX")"
trap 'rm -rf "$WORK"' EXIT

COMMIT="$(git -C "$REPO_ROOT" rev-parse --short HEAD)"
DIRTY=""
if ! git -C "$REPO_ROOT" diff --quiet -- docs/ 2>/dev/null; then
    DIRTY="+uncommitted"
    warn "docs/ has uncommitted changes: output is stamped ${COMMIT}${DIRTY}"
fi
BUILD_DATE="$(date +%Y-%m-%d)"
OPS_STAMP="Generated ${BUILD_DATE} from git ${COMMIT}${DIRTY} — do not edit this file, edit the Markdown in docs/"
USER_STAMP="Version of ${BUILD_DATE}"

pandoc -o "${WORK}/default.docx" --print-default-data-file reference.docx
python3 "$MAKE_REF" "${WORK}/default.docx" "${WORK}/reference.docx" "BIOME-CALC documentation · version of ${BUILD_DATE}" \
    || die "could not build reference.docx"

# Copy one source into the staging tree; with $2=yes append a "Source:" note
# (operator guides only: researchers do not need repo paths). Leading blank
# lines, <!-- path --> comments and one YAML block are dropped, in whichever
# order they appear before the first real line.
stage_source() {
    local rel="$1" with_note="$2" src="${DOCS_DIR}/$1" dst="${WORK}/docs/$1"
    mkdir -p "$(dirname "$dst")"
    awk '
        fm && /^---[[:space:]]*$/                { fm=0; seen_fm=1; next }
        fm                                       { next }
        !started && /^[[:space:]]*$/             { next }
        !started && /^<!--.*-->[[:space:]]*$/    { next }
        !started && !seen_fm && /^---[[:space:]]*$/ { fm=1; next }
        { started=1; print }
    ' "$src" > "$dst"
    if [[ "$with_note" == "yes" ]]; then
        printf '\n\n*Source: `docs/%s`*\n' "$rel" >> "$dst"
    fi
}

built=0
while IFS=$'\t' read -r id title subtitle sources; do
    [[ -z "$id" || "$id" == \#* ]] && continue
    [[ -n "$ONLY" && "$id" != "$ONLY" ]] && continue
    [[ -n "$sources" ]] || die "manifest row '${id}' has no sources"

    read -r -a files <<<"$sources"
    if [[ "$id" == user-* ]]; then note="no"; stamp="$USER_STAMP"; else note="yes"; stamp="$OPS_STAMP"; fi
    meta_args=()
    for f in "${files[@]}"; do
        [[ -f "${DOCS_DIR}/${f}" ]] || die "guide '${id}': source missing: docs/${f}"
        stage_source "$f" "$note"
        meta_args+=(--metadata "wiki_sources=${f}")
    done

    out="${OUT_DIR}/${id}.docx"
    info "building ${id} (${#files[@]} sources) -> ${out}"
    (
        cd "${WORK}/docs"
        pandoc --from=gfm+yaml_metadata_block --to=docx --file-scope \
            --reference-doc="${WORK}/reference.docx" \
            --lua-filter="$FILTER" \
            --resource-path="${DOCS_DIR}/user_guides:${DOCS_DIR}/operations:${DOCS_DIR}/architecture:${DOCS_DIR}/reference:${DOCS_DIR}:${REPO_ROOT}" \
            --metadata title="$title" \
            --metadata subtitle="$subtitle" \
            --metadata date="$stamp" \
            "${meta_args[@]}" \
            -o "$out" "${files[@]}"
    ) || die "pandoc failed for ${id}"
    ok "${id}.docx"
    built=$((built + 1))
done < "$MANIFEST"

[[ "$built" -gt 0 ]] || die "nothing built${ONLY:+ (no manifest id '${ONLY}')}"
ok "${built} guide(s) written to ${OUT_DIR}"
