# ==============================================================================
# pin_r_version.vars.conf
# ==============================================================================
# Configuration variables for pin_r_version.sh
# 
# APT_PREFERENCES_FILE: The file where apt preferences for R will be written.
#                       Default is /etc/apt/preferences.d/r-base.
# R_PACKAGES: Space-separated list of R packages to pin.
#             Default is "r-base r-base-core r-base-dev r-recommended r-cran-*"
# DEFAULT_R_VERSION: The default version of R to pin if the user selects the default option.
#                    Default is "4.6.0".
# ==============================================================================

APT_PREFERENCES_FILE="/etc/apt/preferences.d/r-base"
R_PACKAGES="r-base r-base-core r-base-dev r-recommended r-cran-*"
DEFAULT_R_VERSION="4.6.0"
